version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/project_management_db
      - JWT_SECRET=your_jwt_secret  # Change this to your secret
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: